services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,sqs,lambda,cloudwatch,iam,logs
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
    - "./init-aws:/etc/localstack/init/ready.d" # Runs setup.sh on startup
    - "./lambda:/var/lib/localstack" # Maps your zip file into the container
    - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: localstack
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: csvdb
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"